### PR TITLE
Revert "Clean devDependencies after client is built for package"

### PR DESCRIPTION
**Pull request by ghamaide**
Reverts societe-generale/react-loopback-generator#27

### CODE REVIEW

**Comment by ghamaide** [comment]
@pierpo I reverted it then.

**Comment by pierpo** [comment]
@ghamaide I think it's safer!

**Comment by pierpo** [comment]
@ghamaide I think it's safer!

**Comment by ghamaide** [comment]
@savoisn @pierpo can we merge this PR as it reverts a PR not stable ?

**Pull request merged**
